name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rent-a-car-frontend .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rent-a-car-frontend:latest

  deploy: 
    needs: build
    runs-on: aws-ec2-react    
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/rent-a-car-frontend:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer ${{ secrets.DOCKER_USERNAME }}/rent-a-car-frontend 
